---
title: "HW8"
author: "Jinwoo Jeong"
date: '2022 5 5 '
output:
  pdf_document: default
  html_document: default
---

a)

```{r}
library("factoextra")

set.seed(4052)
a = matrix(rnorm(20*50, mean=0), nrow = 20)
b = matrix(rnorm(20*50, mean=1), nrow = 20)
c = matrix(rnorm(20*50, mean=2), nrow = 20)

data = rbind(a,b,c)
truelabel = c(rep(1,20), rep(2,20), rep(3,20))

data = data.frame(truelabel , data)

```



b)
```{r}
pca = prcomp(data[,-1])$x
plot(pca[,1:2], col=truelabel)
```




c)
```{r}
km = kmeans(data[,-1], centers = 3)
table(km$cluster, data$truelabel)
fviz_cluster(km, data = data ,palette = c("#00AFBB","#2E9FDF","#E7B800"),ggtheme = theme_minimal(),main = "Partitioning Clustering Plot")
```
all of them are well classified 


d)
```{r}
km = kmeans(data[,-1], centers = 2)
table(km$cluster, data$truelabel)

fviz_cluster(km, data = data ,palette = c("#00AFBB","#2E9FDF"),ggtheme = theme_minimal(),main = "Partitioning Clustering Plot")

```

Now the one cluster are combined to the other cluster and rest of groups were well definded 


e)
```{r}
km = kmeans(data[,-1], centers = 4)
table(km$cluster, data$truelabel)
fviz_cluster(km, data = data ,palette = c("#00AFBB","#2E9FDF","#E7B800", "#FC4E07"),ggtheme = theme_minimal(),main = "Partitioning Clustering Plot")
```

Now the one cluster are seperated into two clusters and rest of groups were well definded 
